#!/bin/sh

echo Compressing the needed files
./maketar ~/proverifdemo.tgz
echo Copying the needed files to proverif16.paris.inria.fr
scp local-install ~/proverifdemo.tgz proverif16.paris.inria.fr:
echo Logging into proverif16.paris.inria.fr to install
# Option -t is to force tty allocation even though a command is present, so that sudo can ask for a password
ssh -t proverif16.paris.inria.fr ./local-install